@startuml
enum org.mrp.model.MediaEntryType {
+  MOVIE
+  SERIES
+  GAME
}

class org.mrp.serverHandler.AuthHandler {
~ AuthService authService
+ void handle(HttpExchange)
- void handleRegister(HttpExchange)
- void handleLogin(HttpExchange)
- Map.Entry<String,String> extractCredentials(HttpExchange)
}


class org.mrp.exceptions.InvalidQueryParameterException {
}
class org.mrp.serverHandler.RatingHandler {
~ RatingService ratingService
~ TokenValidation tokenValidation
~ PathParameterExtraction pathParameterExtraction
+ void handle(HttpExchange)
- void handleCreateRating(HttpExchange,UUID)
- void handleUpdateRating(HttpExchange,UUID,UUID)
}


interface org.mrp.repository.Repository {
~ {static} Database db
~ UUID save(T)
~ ResultSet findById(UUID)
~ int delete(UUID)
~ ResultSet findAll()
}


class org.mrp.utils.UUIDGenerator {
+ {static} UUID generateUUIDv7()
+ {static} boolean isValidUUID(String)
+ {static} UUID parseUUID(String)
}

class org.mrp.model.User {
- UUID userId
- String username
- String password_hashed
- int ratings_total
- int favorites_total
- int mediaEntriesCreated_total
- double avgScore
+ String getUsername()
+ void setUsername(String)
+ UUID getUserId()
+ String getPassword_hashed()
+ void setRatings_total(int)
+ void setFavorites_total(int)
+ void setMediaEntriesCreated_total(int)
+ void setAvgScore(double)
+ int getRatings_total()
+ int getFavorites_total()
+ int getMediaEntriesCreated_total()
+ double getAvgScore()
}


class org.mrp.repository.UserRepository {
- MediaEntryService mediaEntryService
+ UUID save(User)
+ void update(String,UUID)
+ UUID getUUID(ResultSet,String)
+ ResultSet findById(UUID)
+ ResultSet findByUsername(String)
+ ResultSet findByToken(String)
+ ResultSet findAll()
+ int delete(UUID)
+ ResultSet getFavoriteMediaEntries(UUID)
+ ResultSet getLeaderboard()
+ boolean isExistingUsername(String)
+ void updateUsername(UUID,String)
+ int getRatings_total(UUID)
+ int getFavorites_total(UUID)
+ int getMediaEntriesCreated_total(UUID)
+ double getAvgScore(UUID)
+ ResultSet getUserTopRatedMediaEntries(UUID)
+ List<MediaEntry> findRecommendations(UUID,List<Genre>,List<MediaEntryType>,List<Integer>)
- void appendINClause(String,List<T>,StringBuilder,List<Object>)
- ResultSet getRecommendationsBasedOnConditions(StringBuilder,List<Object>)
}


class org.mrp.model.Rating {
- UUID id
- UUID userId
- UUID mediaEntryId
- int stars_ct
- String comment
- boolean isCommentVisible
- LocalDateTime timestamp
- List<User> likedBy
+ UUID getId()
+ void setId(UUID)
+ void setUserId(UUID)
+ UUID getUserId()
+ UUID getMediaEntryId()
+ void setMediaEntryId(UUID)
+ String getComment()
+ int getStars_ct()
+ void setStars_ct(int)
+ boolean isCommentVisible()
+ void setCommentVisible()
+ LocalDateTime getTimestamp()
+ List<User> getLikedBy()
+ void setLikedBy(List<User>)
}


class org.mrp.exceptions.ForbiddenException {
}
class org.mrp.model.MediaEntry {
- UUID id
- String title
- String description
- MediaEntryType type
- int releaseYear
- int ageRestriction
- List<Genre> genres
- UUID creatorId
- LocalDateTime createdAt
- double avgRating
+ UUID getId()
+ String getTitle()
+ String getDescription()
+ MediaEntryType getType()
+ int getReleaseYear()
+ int getAgeRestriction()
+ List<Genre> getGenres()
+ UUID getCreatorId()
+ LocalDateTime getCreatedAt()
+ double getAvgRating()
+ void setCreator(UUID)
+ void setId(UUID)
+ void setTitle(String)
+ void setDescription(String)
+ void setType(MediaEntryType)
+ void setReleaseYear(int)
+ void setAgeRestriction(int)
+ void setGenres(List<Genre>)
+ void setCreatedAt(LocalDateTime)
+ void setAvgRating(double)
}


class org.mrp.exceptions.AuthenticationException {
}
class org.mrp.service.RatingService {
- RatingRepository ratingRepository
- MediaEntryRepository mediaEntryRepository
+ String confirmComment(UUID,UUID)
+ Map<String,Object> likeRating(UUID,UUID)
+ Map<String,Object> unlikeRating(UUID,UUID)
+ Map<String,Object> createRating(Rating,UUID)
+ Map<String,Object> updateRating(Rating,UUID,UUID)
+ String deleteRating(UUID,UUID)
- boolean isUserCreator(UUID,UUID)
}


class org.mrp.repository.MediaEntryRepository {
- UUID insertMediaEntry(MediaEntry)
+ UUID save(MediaEntry)
+ UUID getUUID(ResultSet,String)
+ ResultSet findById(UUID)
+ int delete(UUID)
+ ResultSet findAll()
+ ResultSet findAll(Map<String,String>,String)
- void applyFilters(Map<String,String>,StringBuilder,List<Object>)
- void applySorting(String,StringBuilder)
+ Object getCreatorObject(UUID)
- void updateGenres(UUID,List<Genre>)
+ int update(MediaEntry)
+ boolean isFavorite(UUID,UUID)
+ UUID addFavorite(UUID,UUID)
+ int removeFavorite(UUID,UUID)
+ ResultSet getCreated_at(UUID)
}

class org.mrp.exceptions.DuplicateResourceException {
}
class org.mrp.Main {
+ {static} void main(String[])
}

class org.mrp.repository.RatingRepository {
- UUID insertRating(Rating)
+ UUID save(Rating)
- void updateRatingLikes(UUID,List<User>)
+ int update(Rating)
+ ResultSet findById(UUID)
+ int delete(UUID)
+ ResultSet findAll()
+ Object getCreatorObject(UUID)
+ Object getRatingObject(UUID)
+ int changeCommentVisibility(UUID)
+ boolean isAlreadyLikedByUser(UUID,UUID)
+ void addUserLike(UUID,UUID)
+ void removeUserLike(UUID,UUID)
+ ResultSet findByUserId(UUID)
+ ResultSet findByMediaEntryId(UUID)
}

enum org.mrp.model.Genre {
+  ACTION
+  ADVENTURE
+  COMEDY
+  DRAMA
+  THRILLER
+  SCI_FI
+  HORROR
+  FANTASY
+  ROMANCE
+  DOCUMENTARY
+  ANIMATION
}

class org.mrp.service.AuthService {
- UserRepository userRepository
+ Map<String,Object> register(String,String)
+ Map<String,Object> login(String,String)
}


class org.mrp.serverHandler.MediaEntryHandler {
~ MediaEntryService mediaEntryService
~ TokenValidation tokenValidation
~ PathParameterExtraction pathParameterExtraction
+ void handle(HttpExchange)
- void handleCreateMediaEntry(HttpExchange,UUID)
- void handleUpdateMediaEntry(HttpExchange,UUID,UUID)
- void handleGetMediaEntries(HttpExchange,String)
}


class org.mrp.serverHandler.UserHandler {
~ UserService userService
~ TokenValidation tokenValidation
~ PathParameterExtraction pathParameterExtraction
+ void handle(HttpExchange)
- void handleGetProfile(HttpExchange,String)
- void handleUpdateProfile(HttpExchange,String,UUID)
}


class org.mrp.utils.PathParameterExtraction {
+ UUID extractId(HttpExchange,String)
+ String extractUsername(String)
+ T parseRequestOrSendError(HttpExchange,Class<T>)
}

class org.mrp.utils.TokenValidation {
~ UserRepository userRepository
+ UUID validateToken(HttpExchange)
}


enum org.mrp.serverHandler.HttpMethod {
+  POST
+  GET
+  PUT
+  PATCH
+  DELETE
}

class org.mrp.service.MediaEntryService {
- MediaEntryRepository mediaEntryRepository
- RatingRepository ratingRepository
- Set<String> allowedFilters
- Set<String> allowedSorts
- boolean isInvalidType(MediaEntry)
+ Map<String,Object> createMediaEntry(MediaEntry,UUID)
+ Map<String,Object> updateMediaEntry(MediaEntry,UUID,UUID)
- void validateFilters(Map<String,String>)
+ Map<String,Object> getMediaEntries(Map<String,String>,String)
+ MediaEntry mapResultSetToMediaEntry(ResultSet)
+ String deleteMediaEntry(UUID,UUID)
+ String addFavorite(UUID,UUID)
+ String removeFavorite(UUID,UUID)
+ Map<String,Object> getMediaEntryRatings(UUID)
+ Rating mapResultSetToRating(ResultSet)
- boolean isUserCreator(UUID,UUID)
}


class org.mrp.service.UserService {
- UserRepository userRepository
- RatingRepository ratingRepository
- User getUserFromUsername(String)
+ Map<String,Object> getProfile(String)
+ Map<String,Object> updateProfile(String,UUID,Map<String,Object>)
+ Map<String,Object> getFavorites(String)
+ Map<String,Object> getUserRatings(UUID)
+ Rating mapResultSetToRating(ResultSet)
+ List<Map<String,Object>> getLeaderboard()
+ Map<String,Object> getRecommendations(UUID)
- List<K> getTopKeys(Map<K,Integer>,int)
- void incrementCount(Map<K,Integer>,K)
- E toEnum(String,Class<E>)
}


class org.mrp.utils.JsonHelper {
- {static} ObjectMapper mapper
+ {static} T parseRequest(HttpExchange,Class<T>)
+ {static} String toJson(Object)
+ {static} void sendResponse(HttpExchange,int,Object)
+ {static} void sendError(HttpExchange,int,String)
+ {static} void sendSuccess(HttpExchange,String)
+ {static} Map<String,String> parseQueryParams(String)
}


class org.mrp.database.Database {
- String url
- String user
- String password
- Connection connection
- void connect()
+ Connection getConnection()
+ ResultSet query(String,Object)
+ int update(String,Object)
+ UUID insert(String,Object)
+ void insertWithoutUUID(String,Object)
+ boolean exists(String,Object)
- PreparedStatement prepareStatement(String,Object)
- void setParameters(PreparedStatement,Object)
+ UUID getUUID(ResultSet,String)
+ void close()
+ Object getValue(String,Object)
}




com.sun.net.httpserver.HttpHandler <|.. org.mrp.serverHandler.AuthHandler
org.mrp.exceptions.RuntimeException <|-- org.mrp.exceptions.InvalidQueryParameterException
com.sun.net.httpserver.HttpHandler <|.. org.mrp.serverHandler.RatingHandler
org.mrp.repository.Repository <|.. org.mrp.repository.UserRepository
org.mrp.exceptions.RuntimeException <|-- org.mrp.exceptions.ForbiddenException
org.mrp.exceptions.RuntimeException <|-- org.mrp.exceptions.AuthenticationException
org.mrp.repository.Repository <|.. org.mrp.repository.MediaEntryRepository
org.mrp.exceptions.RuntimeException <|-- org.mrp.exceptions.DuplicateResourceException
org.mrp.repository.Repository <|.. org.mrp.repository.RatingRepository
com.sun.net.httpserver.HttpHandler <|.. org.mrp.serverHandler.MediaEntryHandler
com.sun.net.httpserver.HttpHandler <|.. org.mrp.serverHandler.UserHandler
@enduml